### ISSUE TITLE
spoint.online bug

### ISSUE THREAD

**Issue by RichardDrent** [98oktay/oktaybaskus#3]
hi,

I think spoint.online is yours, its a great tool.

but some bugs we found.
- the site on firefox is showing the value of the carts before they are flipped over
- the app on Iphone when the use had a 3 latter name (example Pat) the app does not show on the site.

Richard

**Comment by 98oktay** [comment]
Hi Richard,
Thank you for your interest in my project.

We quickly corrected the Firefox error that escaped our attention.
I will also release a new update on the 3-latter name issue.

I'm glad you gave feedback. I hope this app is useful.

**Comment by RichardDrent** [comment]
that's great news. if we bump into more issues. i will let you know.

i will introduce it to the other dev teams, when all is working fine.

r.
