### ISSUE TITLE
Spoint.online improvement

### ISSUE THREAD

**Issue by RichardDrent** [98oktay/oktaybaskus#4]
Hi,

my team is a big fan of your app, and we are even carrying it to other teams in the company.

3 things that can be improved a bit.

on the site what is showing the results
1) the console is throwing an error 
Array.from(document.querySelectorAll('.pokerCardItem-selected')).map(x=>x.innerHTML)

2) the names of the team members is not good readable when the cards are turned around
we voted on having the names the same as they are when the cards are not turned around

3) as a bunch of development nerds are using it, and trying to hack it to have the Advantage of knowing the points given by the other team members. 
so as a future improvement you could look into the possibility to encrypt or randomize the story points in the code behind.

thanks again

Richard

**Comment by 98oktay** [comment]
Hi Richard,

Thank you for your good ideas and advice. I am very happy that you liked my app. I worked a little on what you suggested. Now I think it is better and safer. I am open to suggestions to make it more beautiful.

However, the number of people who scored my App Store and Play Store is very low. We have been live without advertising for 1 year. Please support we in rating appstore and playstore. 🙏

Thanks.

**Comment by RichardDrent** [comment]
we will write something, and some already did.

post it on a Scrum forum as the perfect Covid working from home solution. 

R.

**Comment by 98oktay** [comment]
Hello, 

We moved site to new domain: www.spoint-online.com

Thanks.
